version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    env_file:
      - ./.env
    depends_on:
      - mongodb

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 8000:8000
    depends_on:
      - api

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 443:443
      - 80:80
    depends_on:
      - api
      - client

  mongodb:
    image: mongo:3.4
    restart: always
    env_file:
      - ./.env
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
