version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    env_file:
      - ./.env
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      - mongodb

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - 8000:8000
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - api

  mongodb:
    image: mongo:3.4
    restart: always
    env_file:
      - ./.env
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
